spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

profiles:
  active: railway

jwt:
  secret: ${JWT_SECRET:b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu}
  expiration: ${JWT_EXPIRATION:3000}

# 오피스텔 API 설정
officetel:
  api:
    service-key: ${OFFICETEL_API_SERVICE_KEY:59afac38869bae8eb4bf96349cc3f88340e584d290b52c74a600c4053b856212}
    base-url: https://apis.data.go.kr/1613000/RTMSDataSvcOffiRent/getRTMSDataSvcOffiRent
    request:
      max-rows: 100
      months-to-fetch: 3
      timeout: 10s

# VWorld Geocoding API 설정 (GPS 좌표 -> 주소 변환)
vworld:
  api:
    key: ${VWORLD_API_KEY:D2B43972-B325-3DEF-9F41-FF3316FD3AB0}
    url: https://rental-lovat-theta.vercel.app/api/vworld-proxy
    enabled: ${VWORLD_API_ENABLED:true}

# 정책 API 설정 (해커톤용 - 추후 확장 가능)
policy:
  api:
    cache-duration: 3600  # 1시간 캐시
    max-results: 50       # 최대 결과 수
    default-region: "전국" # 기본 지역

server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 0

# 로깅 설정
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.example.seasontonebackend: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Railway 환경변수 디버깅을 위한 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

# Google OAuth2 Client
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope:
              - profile
              - email

