spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

jwt:
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000

# 오피스텔 API 설정
officetel:
  api:
    service-key: e20aoTYyOLpe4UPR3I70w+QLG5abe/L7o0QOJ4bOpnyRTZcTFrYAKb/MVp+/lNY8IMzLLdvjvf6BRGb7Tpa2OA==
    base-url: https://apis.data.go.kr/1613000/RTMSDataSvcOffiRent/getRTMSDataSvcOffiRent
    request:
      max-rows: 100
      months-to-fetch: 3
      timeout: 10s


# VWorld Geocoding API 설정 (GPS 좌표 -> 주소 변환)
vworld:
  api:
    key: D2B43972-B325-3DEF-9F41-FF3316FD3AB0
    url: http://api.vworld.kr/req/address


# 정책 API 설정 (해커톤용 - 추후 확장 가능)
policy:
  api:
    cache-duration: 3600  # 1시간 캐시
    max-results: 50       # 최대 결과 수
    default-region: "전국" # 기본 지역

server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 0

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: kwh0912@gmail.com
    password: pccvzejninsyynmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
