spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seasonton?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    database: mysql
    #    InnoDB??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

jwt:
  #   32?? ?? ???? ??? : oauthserversecretaccesstokenoauthserversecretaccesstokenoauthserversecretaccesstoken
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000 #???

# 오피스텔 API 설정
officetel:
  api:
    # 환경변수로 설정하거나 외부 설정 파일에서 로드
    service-key: ${OFFICETEL_API_KEY:default_key}
    base-url: https://apis.data.go.kr/1613000/RTMSDataSvcOffiRent/getRTMSDataSvcOffiRent
    request:
      max-rows: 100
      months-to-fetch: 3
      timeout: 10s
